# prometheus.yml
global:
  scrape_interval: 15s # Busca dados a cada 15 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # Nosso alvo de infraestrutura
    static_configs:
      - targets: ['node-exporter:9100']

      