# prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-votacao'
    static_configs:
      - targets: ['app-votacao:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']


